package by.htp.parse.parser.sax;

public enum SaxTagName {
	TITLE, YEAR, COUNT, COUNTDAYS, NAME, SURNAME, AUTHOR, AUTHORS,  EDITOR, EDITORS, MAGAZINE, MAGAZINES, BOOK, BOOKS, NEWSPAPER, NEWSPAPERS, LIBRARY

}
